version: '3'
services:
  hrm-api:
    #    image: 'hrm'
    build:
      context: .
      dockerfile: webapp.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/HRM
    links:
      - "testdatabase"
    depends_on:
      - testdatabase
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testdatabase:5432/hrm_db
  testdatabase:
    #    image: 'database'
    build:
      context: .
      dockerfile: db.Dockerfile
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648


