version: '3'
services:
  hrm-api:
    #    image: 'hrm'
    build:
      context: .
      dockerfile: webapp.Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/HRM
    links:
      - "testdatabase"
    depends_on:
      - testdatabase
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testdatabase:5432/hrm_db
  testdatabase:
    #    image: 'database'
    build:
      context: .
      dockerfile: db.Dockerfile