create table position(
    id int primary key generated by default as identity,
    "name" varchar(30)
);

create table person(
    id int primary key generated by default as identity,
    first_name varchar(30) not null,
    last_name varchar(30) not null,
    email varchar(30) unique not null,
    is_active boolean,
    position int references position(id) on delete set null
);

create table unit(
    "name" varchar(30) primary key,
    parent_unit varchar(30)
);

create table unit_person(
    person_id int references person(id) on delete cascade,
    unit_name varchar(30) references unit("name") on delete cascade
);

insert into position(name) values ('manager');

insert into position(name) values ('engeneer');
