version: '1'
services:
  hrm-api:
    image: 'hrm'
    ports:
      - "8080:8080"
    links:
      - "testdatabase"
    depends_on:
          - testdatabase
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testdatabase:5432/hrm_db
  testdatabase:
    image: 'database'